### ISSUE TITLE
ACTIVIDAD8_MODELO EN WEBASSEMBLY

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/actividad-8-modelo-en-webassembly-equipo-judith#2]
[Actividad 8 Modelo en WebAssembly.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-modelo-en-webassembly-equipo-judith/files/11594153/Actividad.8.Modelo.en.WebAssembly.pdf)

**Comment by Gregorio012** [comment]
Calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
